services:
  - type: web
    name: my-u-lib-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        value: django-insecure-fvj%33(yz63ii9*b7o6(9t*b@#5-@ejt9&na_10*+8iwlgwzp2
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: my-u-lib-db
          property: connectionString
